eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka

server:
  port: 8085
      
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: cartmodule
        uri: http://localhost:8081
        predicates:
        - Path=/cart-service/**
        filters:
        - StripPrefix=1

      - id: productmodule
        uri: http://localhost:8082
        predicates:
        - Path=/product-service/**
        filters:
        - StripPrefix=1

      - id: usermodule
        uri: http://localhost:8083
        predicates:
        - Path=/user-service/**
        filters:
        - StripPrefix=1
                
      - id: invoicemodule
        uri: http://localhost:8084
        predicates:
        - Path=/invoice-service/**
        filters:
        - StripPrefix=1